import os, sys, psycopg2; sys.stdout.reconfigure(encoding='utf-8')
from dotenv import load_dotenv; load_dotenv('.env')
conn = psycopg2.connect(host=os.environ['PGHOST'], dbname=os.environ['PGDATABASE'], user=os.environ['PGUSER'], password=os.environ['PGPASSWORD'])
cur = conn.cursor()
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name='party' ORDER BY ordinal_position")
print('party columns:', [r[0] for r in cur.fetchall()])
cur.execute('SELECT id, name FROM party LIMIT 5')
for r in cur.fetchall(): print(r)
conn.close()
